USE dcdb;

SET
  @SlotTypeMain = 1,
  @SlotTypeOffense = 2,
  @SlotTypeDefense = 3,
  @SlotTypeUtility = 4,
  @MatTypeCloth = 1,
  @MatTypeLeather = 2,
  @MatTypeMetal = 3;

INSERT INTO Slot (SchematicId, SlotTypeId, MaterialTypeId, Quantity) VALUES
	(1,@SlotTypeMain,@MatTypeMetal,12),
	(1,@SlotTypeOffense,@MatTypeMetal,6),
	(1,@SlotTypeOffense,@MatTypeMetal,4),
	(1,@SlotTypeOffense,@MatTypeMetal,4),
	(2,@SlotTypeMain,@MatTypeMetal,22),
	(2,@SlotTypeOffense,@MatTypeMetal,16),
	(2,@SlotTypeOffense,@MatTypeCloth,12),
	(2,@SlotTypeUtility,@MatTypeMetal,6),
	(3,@SlotTypeMain,@MatTypeMetal,24),
	(3,@SlotTypeOffense,@MatTypeCloth,8),
	(3,@SlotTypeOffense,@MatTypeMetal,6),
	(3,@SlotTypeOffense,@MatTypeCloth,8),
	(4,@SlotTypeMain,@MatTypeMetal,14),
	(4,@SlotTypeOffense,@MatTypeMetal,8),
	(4,@SlotTypeOffense,@MatTypeLeather,4),
	(4,@SlotTypeOffense,@MatTypeMetal,4),
	(5,@SlotTypeMain,@MatTypeMetal,24),
	(5,@SlotTypeOffense,@MatTypeLeather,20),
	(5,@SlotTypeUtility,@MatTypeLeather,12),
	(5,@SlotTypeOffense,@MatTypeMetal,6),
	(6,@SlotTypeMain,@MatTypeMetal,24),
	(6,@SlotTypeOffense,@MatTypeMetal,10),
	(6,@SlotTypeOffense,@MatTypeLeather,8),
	(6,@SlotTypeUtility,@MatTypeLeather,8),
	(7,@SlotTypeMain,@MatTypeMetal,8),
	(7,@SlotTypeDefense,@MatTypeMetal,12),
	(7,@SlotTypeDefense,@MatTypeLeather,5),
	(8,@SlotTypeMain,@MatTypeCloth,4),
	(8,@SlotTypeDefense,@MatTypeCloth,12),
	(9,@SlotTypeMain,@MatTypeMetal,5),
	(9,@SlotTypeDefense,@MatTypeCloth,12),
	(10,@SlotTypeMain,@MatTypeMetal,5),
	(10,@SlotTypeUtility,@MatTypeMetal,12),
	(11,@SlotTypeMain,@MatTypeCloth,21),
	(11,@SlotTypeUtility,@MatTypeCloth,6),
	(11,@SlotTypeDefense,@MatTypeMetal,4),
	(11,@SlotTypeUtility,@MatTypeLeather,4),
	(12,@SlotTypeMain,@MatTypeLeather,21),
	(12,@SlotTypeUtility,@MatTypeLeather,5),
	(12,@SlotTypeUtility,@MatTypeLeather,4),
	(12,@SlotTypeDefense,@MatTypeMetal,5),
	(13,@SlotTypeMain,@MatTypeMetal,21),
	(13,@SlotTypeUtility,@MatTypeMetal,6),
	(13,@SlotTypeDefense,@MatTypeLeather,4),
	(13,@SlotTypeDefense,@MatTypeLeather,4),
	(14,@SlotTypeMain,@MatTypeMetal,21),
	(14,@SlotTypeDefense,@MatTypeMetal,6),
	(14,@SlotTypeDefense,@MatTypeLeather,5),
	(14,@SlotTypeDefense,@MatTypeCloth,5),
	(15,@SlotTypeUtility,@MatTypeCloth,8),
	(15,@SlotTypeDefense,@MatTypeCloth,4),
	(16,@SlotTypeUtility,@MatTypeCloth,8),
	(16,@SlotTypeDefense,@MatTypeCloth,4),
	(17,@SlotTypeUtility,@MatTypeLeather,8),
	(17,@SlotTypeDefense,@MatTypeLeather,4),
	(18,@SlotTypeUtility,@MatTypeLeather,6),
	(18,@SlotTypeDefense,@MatTypeMetal,3),
	(19,@SlotTypeUtility,@MatTypeMetal,8),
	(19,@SlotTypeDefense,@MatTypeMetal,4),
	(20,@SlotTypeUtility,@MatTypeMetal,8),
	(20,@SlotTypeDefense,@MatTypeLeather,4),
	(21,@SlotTypeDefense,@MatTypeMetal,8),
	(21,@SlotTypeDefense,@MatTypeMetal,4),
	(22,@SlotTypeDefense,@MatTypeMetal,8),
	(22,@SlotTypeDefense,@MatTypeLeather,4);
